sudo: required

addons:
  postgresql: "9.4"

services:
  - docker
  - postgresql

language: python

python: "3.5"

env:
  global:
    - RESOLWE_POSTGRESQL_USER=postgres
    - RESOLWE_POSTGRESQL_PORT=5432
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=packaging

install: pip install tox

script: tox -e $TOX_ENV
